### PR TITLE
Screenshot tests

### PR DESCRIPTION
**Pull request by vxsx**
no screenshot tests for pagetree, as we're gonna change it in 3.3 anyway

i stopped all the builds except integration tests (we anyway have to merge this into develop-3.4 and from there into the upstream repo)

### CODE REVIEW

**Comment by FinalAngel** [comment]
LGTM

**Comment by vxsx** [comment]
ok so the problem here is the screenshots were made originally on osx, and travis is running on ubuntu

| reference | travis | diff |
| -------------| --------|-----|
| login-form-error | login-form-error diff | login-form-error fail |

**Comment by vxsx** [comment]
I guess the solution is **docker** but my know-how is lacking on how to do that nicely

**Comment by vxsx** [comment]
@FinalAngel @intellectronica any thoughts on how to implement this?

**Comment by FinalAngel** [comment]
bye bye screenshot tests :(

**Pull request closed without merging**
