### PR TITLE
Port to libsass

### PR DESCRIPTION
**Pull request by FinalAngel**
This PR migrates from ruby-sass/compass to libsass

image

- Adding Node.js
- Adding Gulp
- Adding libsass

### CODE REVIEW

**Comment by yakky** [comment]
:+1:

**Comment by driesdesmet** [comment]
What about @jrief's idea of prepocessing the css at build time? Is setuptools up to the task of running gulp through setup.py? I'm considering this workflow for my own projects, but so far I have been lazy and kept my generated css under version control.

**Comment by FinalAngel** [comment]
@driesdesmet our approach is to compile the css either on deployment, or as soon as you run the server through a `Makefile`. We did that already for sass/compass (as there are packages available) though it's an entire thing with libsass (as autoprefixer support is missing) so it requires you to have node installed on the server (still far more preferable than ruby for us).

You can check a good example here: https://github.com/divio/django-cms-demo

**Comment by jrief** [comment]
@driesdesmet storing autogenerated files in a VCS is bad practice. Therefore my proposal for external  CSS- and JS-libraries, which are available via bower or npm, is to only keep a reference to those libs via bower.json / package.json. On the final system these packages then can be installed via Python using  https://github.com/jrief/django-nodebow

Well, its not pure Python, because it uses PyExecJS, but at least you get one single entry point in your Django's ``./manage.py``. Unfortunately, PyExecJS has some issues with bower prompting in case of version mismatch. Therefore, when I have some time, I'll change it to a Python system call.

**Comment by driesdesmet** [comment]
@FinalAngel I hadn't come across that demo. Thanks for the link. So, 'make' as another tool on top of gulp. Interesting. I had considered it, but didn't want to learn Make syntax (although it doesn't look that complicated from your example). Ideally I'd like to limit the tools I need to maintain, or learn them once and then forget about them: django's management commands, Make, gulp, Fabric, python packaging... that list is getting long. Now I've started throwing docker into the the mix...

@jrief I haven't looked at your project, but I will. It's comforting at least to know that other people find that there is room for improvement. However, I'm also cautious about tools that are wrappers around existing tools. You often end up learning the underlying tools, which defeats the purpose. Take django-bower for example. It works well, but keeps relying on node. I can't do the 'bower install --save' thingy. Then I wondered, bower is just a repo with static files to download, could those package be on pypi as well, with a bower prefix for example?

I know I'm throwing a lot of different purpose things on one pile here. I just wanted to vent my slight frustration that it all feels complicated, far more complicated than writing actual django code.

**Comment by FinalAngel** [comment]
@driesdesmet thats why we decided on having some ground rules on how to run things (https://github.com/divio/divio-architect). Having all those commands - depending on which field you are coming from - it's tricky to learn and handle them properly.

We use the Makefile for mainstreaming all those processes into a few simple commands. Each department then has their own set of "meta" tools. But in the end backend doesn't have to worry how frontend builds their stack, you just have to run `make install` or `make run`.

**Comment by jrief** [comment]
@driesdesmet 
this discussion is interesting, but becomes off-topic on this channel. Please start an issue by copy&pasting your concerns onto  https://github.com/jrief/django-nodebow/issues , so that we can proceed there.

**Pull request merged**
